"""Add payment reference to purchases

Revision ID: 15c60086ae9f
Revises: 5e2707b04097
Create Date: 2026-07-22 16:22:13.061525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c60086ae9f'
down_revision: Union[str, Sequence[str], None] = '5e2707b04097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('payment_reference', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_purchases_payment_reference'), 'purchases', ['payment_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_payment_reference'), table_name='purchases')
    op.drop_column('purchases', 'payment_reference')
    # ### end Alembic commands ###
